version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:v1
    networks: 
     - inception
    build:
     context: requirements/mariadb/
     dockerfile: Dockerfile
    env_file: .env
    volumes:
     - mariadb:/var/lib/mysql/
    restart: unless-stopped
    expose:
     - "3306"

  nginx:
    container_name: nginx
    image: nginx:v1
    networks:
     - inception
    build:
     context: requirements/nginx/
     dockerfile: Dockerfile
    env_file: .env
    volumes:
     - wordpress:/var/www/html
    depends_on:
     - wordpress
    restart: unless-stopped
    ports:
     - 443:443

  wordpress:
    container_name: wordpress
    image: wordpress:v1
    networks:
     - inception
    build:
     context: requirements/wordpress/
     dockerfile: Dockerfile
    env_file: .env
    volumes:
     - wordpress:/var/www/wordpress
    depends_on:
     - mariadb
    restart: unless-stopped
    expose: 
    - "9000"



volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
     type: 'none'
     o: bind
     device: '/home/abelmoha/data/wordpress'
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
     type: 'none'
     o: bind
     device: '/home/abelmoha/data/mariadb'
networks:
  inception:
   driver: bridge